import { Agent } from '@credo-ts/core';
import AgentProvider from '@credo-ts/react-hooks';
import createApp from './App';
import * as components from './components';
import { ButtonImpl as Button, ButtonType } from './components/buttons/Button';
import IconButton, { ButtonLocation } from './components/buttons/IconButton';
import BulletPoint from './components/inputs/BulletPoint';
import CheckBoxRow from './components/inputs/CheckBoxRow';
import LimitedTextInput from './components/inputs/LimitedTextInput';
import PINInput from './components/inputs/PINInput';
import NotificationListItem from './components/listItems/NotificationListItem';
import ContentGradient from './components/misc/ContentGradient';
import CredentialCard from './components/misc/CredentialCard';
import ErrorBoundaryWrapper from './components/misc/ErrorBoundary';
import FauxHeader from './components/misc/FauxHeader';
import InfoBox, { InfoBoxType } from './components/misc/InfoBox';
import QRRenderer from './components/misc/QRRenderer';
import QRScannerTorch from './components/misc/QRScannerTorch';
import ScanCamera from './components/misc/ScanCamera';
import SVGOverlay, { MaskType } from './components/misc/SVGOverlay';
import DeveloperModal from './components/modals/DeveloperModal';
import DismissiblePopupModal from './components/modals/DismissiblePopupModal';
import ErrorModal from './components/modals/ErrorModal';
import SafeAreaModal from './components/modals/SafeAreaModal';
import Record from './components/record/Record';
import InfoTextBox from './components/texts/InfoTextBox';
import Link from './components/texts/Link';
import Text from './components/texts/Text';
import { ThemedText } from './components/texts/ThemedText';
import { ToastType } from './components/toast/BaseToast';
import toastConfig from './components/toast/ToastConfig';
import { AttachTourStep } from './components/tour/AttachTourStep';
import { credentialOfferTourSteps } from './components/tour/CredentialOfferTourSteps';
import { credentialsTourSteps } from './components/tour/CredentialsTourSteps';
import { homeTourSteps } from './components/tour/HomeTourSteps';
import { proofRequestTourSteps } from './components/tour/ProofRequestTourSteps';
import { TourBox } from './components/tour/TourBox';
import { Banner, BannerSection } from './components/views/Banner';
import HomeFooterView from './components/views/HomeFooterView';
import KeyboardView from './components/views/KeyboardView';
import ScreenWrapper from './components/views/ScreenWrapper';
import { attemptLockoutConfig, PINRules, tours, walletTimeout, minPINLength } from './constants';
import { defaultConfig, defaultHistoryEventsLogger } from './container-impl';
import * as contexts from './contexts';
import { ActivityProvider, AutoLockTime, useActivity } from './contexts/activity';
import { AuthProvider } from './contexts/auth';
import NavContainer from './contexts/navigation';
import { NetworkProvider } from './contexts/network';
import { useTour } from './contexts/tour/tour-context';
import { TourProvider } from './contexts/tour/tour-provider';
import { useDeveloperMode } from './hooks/developer-mode';
import usePreventScreenCapture from './hooks/screen-capture';
import useBifoldAgentSetup from './hooks/useBifoldAgentSetup';
import { OpenIDCredentialRecordProvider } from './modules/openid/context/OpenIDCredentialRecordProvider';
import { DefaultScreenLayoutOptions } from './navigators/defaultLayoutOptions';
import { DefaultScreenOptionsDictionary, useDefaultStackOptions } from './navigators/defaultStackOptions';
import AttemptLockout from './screens/AttemptLockout';
import Biometry from './screens/Biometry';
import Developer from './screens/Developer';
import Onboarding from './screens/Onboarding';
import OnboardingPages from './screens/OnboardingPages';
import Preface from './screens/Preface';
import Scan from './screens/Scan';
import Splash from './screens/Splash';
import Terms from './screens/Terms';
import UpdateAvailable from './screens/UpdateAvailable';
import VideoCall from './screens/VideoCall';
import IncomingCall from './screens/IncomingCall';
import { AbstractBifoldLogger } from './services/AbstractBifoldLogger';
import { bifoldLoggerInstance } from './services/bifoldLogger';
import { isBiometricsActive, loadLoginAttempt, loadWalletSalt, storeWalletSecret } from './services/keychain';
import { hashPIN } from './utils/crypto';
import { BifoldLogger } from './services/logger';
import { MockLogger } from './testing/MockLogger';
import { ThemeBuilder } from './theme-builder';
import * as types from './types';
import { QrCodeScanError } from './types/error';
import { RefreshOrchestrator } from './modules/openid/refresh/refreshOrchestrator';
import { AgentBridge } from './services/AgentBridge';
import * as workflow from './modules/workflow';
// Workflow hooks
import { useWorkflowEvents, useWorkflowInstanceEvents, useNewWorkflowEvents } from './hooks/useWorkflowEvents';
import { useWorkflows, useWorkflowTemplates, usePendingWorkflows } from './hooks/useWorkflows';
import { useWorkflowInstance } from './hooks/useWorkflowInstance';
// WebRTC hooks
import { useCallService } from './hooks/useCallService';
import { useWebRTCEvents } from './hooks/useWebRTCEvents';
import { useIncomingCallHandler } from './hooks/useIncomingCallHandler';
import { useConnectionCapabilities, checkWebRTCSupport, clearCapabilityCache } from './hooks/useConnectionCapabilities';
// Services
import { MobileWorkflowService } from './services/WorkflowService';
import { CallService } from './services/CallService';
export { animatedComponents } from './animated-components';
export { EventTypes, LocalStorageKeys } from './constants';
export { AnimatedComponentsProvider, useAnimatedComponents } from './contexts/animated-components';
export { useAuth } from './contexts/auth';
export { useNetwork } from './contexts/network';
export { DispatchAction, reducer, default as Store } from './contexts/reducers/store';
export { defaultState, mergeReducers, StoreContext, StoreProvider, useStore } from './contexts/store';
export { ThemeProvider, useTheme } from './contexts/theme';
export { useDeepLinks } from './hooks/deep-links';
export { initLanguages, initStoredLanguage, Locales, translationResources } from './localization';
export * from './navigators';
export { createStyles } from './screens/OnboardingPages';
export * from './services/storage';
export { bifoldTheme, ColorPalette, Assets as ImageAssets } from './theme';
export * from './types/attestation';
export { BifoldError } from './types/error';
export { Screens, Stacks, TabStacks } from './types/navigators';
export * from './types/version-check';
export { createLinkSecretIfRequired, getAgentModules } from './utils/agent';
export { getCredentialIdentifiers, isValidAnonCredsCredential } from './utils/credential';
export { connectFromScanOrDeepLink, formatTime, getConnectionName, removeExistingInvitationsById, useCredentialConnectionLabel, } from './utils/helpers';
export { getIndyLedgers, IndyLedger, readIndyLedgersFromFile, writeIndyLedgersToFile } from './utils/ledger';
export { statusBarStyleForColor, StatusBarStyles } from './utils/luminance';
export { migrateToAskar } from './utils/migration';
export { buildFieldsFromAnonCredsCredential } from './utils/oca';
export { KanonOCABundleResolver, createKanonOCABundleResolver } from './utils/KanonOCABundleResolver';
export { testIdForAccessabilityLabel, testIdWithKey } from './utils/testable';
export { BasicMessageMetadata, CredentialMetadata } from './types/metadata';
export { InlineErrorPosition } from './types/error';
export * from './container-api';
export { MainContainer } from './container-impl';
export { LockoutReason } from './contexts/auth';
export { BaseTourID } from './types/tour';
// Workflow module exports
export * from './modules/workflow';
export { workflow };
export { AbstractBifoldLogger, ActivityProvider, Agent, AgentProvider, AttachTourStep, AttemptLockout, attemptLockoutConfig, AuthProvider, AutoLockTime, Banner, BannerSection, BifoldLogger, bifoldLoggerInstance, Biometry, BulletPoint, Button, ButtonLocation, ButtonType, CheckBoxRow, components, ContentGradient, contexts, createApp, CredentialCard, credentialOfferTourSteps, credentialsTourSteps, defaultConfig, defaultHistoryEventsLogger, DefaultScreenLayoutOptions, DefaultScreenOptionsDictionary, Developer, DeveloperModal, DismissiblePopupModal, ErrorBoundaryWrapper, ErrorModal, FauxHeader, HomeFooterView as HomeContentView, homeTourSteps, IconButton, InfoBox, InfoBoxType, InfoTextBox, isBiometricsActive, KeyboardView, LimitedTextInput, Link, loadLoginAttempt, loadWalletSalt, storeWalletSecret, hashPIN, MaskType, MockLogger, NavContainer, NetworkProvider, NotificationListItem, Onboarding, OnboardingPages, OpenIDCredentialRecordProvider, PINInput, PINRules, minPINLength, Preface, proofRequestTourSteps, QrCodeScanError, QRRenderer, QRScannerTorch, Record, SafeAreaModal, Scan, ScanCamera, ScreenWrapper, Splash, SVGOverlay, Terms, Text, ThemeBuilder, ThemedText, toastConfig, ToastType, TourBox, TourProvider, tours, types, UpdateAvailable, VideoCall, IncomingCall, useActivity, useBifoldAgentSetup, useDefaultStackOptions, useDeveloperMode, usePreventScreenCapture, useTour, walletTimeout, RefreshOrchestrator, AgentBridge, 
// Workflow hooks
useWorkflowEvents, useWorkflowInstanceEvents, useNewWorkflowEvents, useWorkflows, useWorkflowTemplates, usePendingWorkflows, useWorkflowInstance, 
// WebRTC hooks
useCallService, useWebRTCEvents, useIncomingCallHandler, useConnectionCapabilities, checkWebRTCSupport, clearCapabilityCache, 
// Services
MobileWorkflowService, CallService, };
export { ProtocolURIs } from './hooks/useConnectionCapabilities';
